# generated by datamodel-codegen:
#   filename:  settings.schema.jsonc
#   timestamp: 2026-04-23T22:07:37+00:00

from __future__ import annotations

from typing import Any, Literal

from typing_extensions import NotRequired, TypedDict


class Settings(TypedDict, closed=True):
  defaultBrowser: NotRequired[str]
  hideEmptyProperties: NotRequired[bool]
  closeOnFocusLoss: NotRequired[bool]
  alwaysOnTop: NotRequired[bool]
  closeOnEscPressed: NotRequired[bool]
  closeOnEscPressedAnywhere: NotRequired[bool]
  titleBar: NotRequired[
    Literal['shown', 'hidden', 'toggle start hidden', 'toggle start shown']
  ]


class Rule(TypedDict, closed=True):
  matches: list[
    tuple[
      Literal[
        'url',
        'protocol',
        'fulldomain',
        'tld',
        'subdomain',
        'maindomainonly',
        'maindomain',
        'parentprocesspath',
        'path',
        'perams',
        'port',
        'hash',
        'fileName',
        'drive',
        'FileExt',
        'FileName And Ext',
      ]
      ,Literal[
        'is', 'matchesregex', 'isexact', 'startswith', 'endswith', 'includes'
      ]
      ,str
    ]
  ]
  name: str


Model = TypedDict(
  'Model',
  {
    'settings': Settings,
    'programs': Any,
    '$schema': NotRequired[str],
    'rules': list[Rule],
  },
  closed=True,
)


class Programdefault(TypedDict, closed=True):
  args: NotRequired[list[str]]
  path: NotRequired[str | list[str]]
  visible: NotRequired[bool]
  admin: NotRequired[bool]
  fallback: NotRequired[str | list[str]]
